language: python
cache: pip

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6
    - env: TOXENV=py27-dj111
      python: 2.7
    - env: TOXENV=py36-dj111
      python: 3.6
    - env: TOXENV=py36-dj20
      python: 3.6
    - env: TOXENV=docs
      python: 3.6

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls

deploy:
  - provider: pypi
    skip-cleanup: true
    distributions: "sdist bdist_wheel --universal"
    user: cfpb
    password:
      secure: "IdkZRJrqQHpjloKJ2Be2AJwdt/udxPqmu1koav63zBsqjSMMDPUWl+KBbXwFhhdKJN/r7U3hnLKEtn3ia1we0hMwsQ372Z6aho/FvCA8UbNjLoT3cXIwHWxcXZfOcInctpvn8cOMjJfQBlMe2FnuAWa44zn+9U8g3ujF6xajbxGXYgpbuqWmitizVDACw85ZyFY8sgFvIfK8pVeyffWG0WPp7QXlS48HI+LjmWK6jAz4M4bu6nvgsbEHVZ72bIKfLhw+Gx4EJ+P0CTh2nFgZ9d1MOYlv8HF8G9c5ZE865XdLmsI5uxhaXr8HSgEQkFVjk9Q6v54SI1FVuvcpa88HOMbctqoVZ+OLczHh9ibreqYe1I0Zstd51uChDCP624VH4pOo7lmLe5yVug25m5iyG5lXaiXd5r0tQUM5SduleG1twFCZU2TcD0JvG9FhCZXP3fAvk2IMad4cn65EFKbEgCVzCQSUSNmQ6y4bqTg7nTgyG7KKjeKw74bOnsvsUWUcul1KlJcpUefKelLPYVKvdk7jT+W8vhx/ihrywcoRSCOZ476ut0js7o7wBBFSPlGdvxPCkfzjJswMmZWgiq5Kkjo8oWrFKCvjDJd5Aro1+8AnVR8PqpxLW1drX5H5zKCL16zDOWmyWYc2M+Us0I7d4ZgygU77FnfUG7u52JC679I="
    on:
      tags: true
      condition: $TOXENV = "py36-dj111"
  - provider: pages
    local_dir: site
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      condition: $TOXENV = "docs"
