language: python
cache: pip

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6
    - env: TOXENV=py27-dj111
      python: 2.7
    - env: TOXENV=py36-dj111
      python: 3.6
    - env: TOXENV=py36-dj20
      python: 3.6
    - env: TOXENV=docs
      python: 3.6

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls

deploy:
  - provider: pypi
    skip-cleanup: true
    distributions: "sdist bdist_wheel --universal"
    user: cfpb
    password:
      secure: "Wr1Cv8sjYdfsW9QZ7RiKhwd4R+0XATFRzZ6emj1TBq5YODFmKpBfaAd+L2E4jL/yBzqws2R/U0H1u4AAXarQVTwYTXIQGeXy1AgJr45l1v1JH1uXFaSj5O+j3uVO5mNoDdZIblEH4kQ62+1TCsoCW8+l726oU2DhKcGGHOgSfUoX/cZewO5fZm/r3Yp/Y5FY3brJhB/89WEvaoBoB2WRuDP9cPD9Kf5SgaDZp3ak4EVtrTBRaFZkPi5QVqNrRa15Sv6WrQ7AqBRq1vPuTfTSj+iKCzPebeASMIb43BCgcKGnsh+ImUF+HlZyymSTfVGm/7hFgNemF6gWVeQ86sft31rrEqQNJFu5Y4HRDKRoj4MpBsluqGkcy7R/abpUeEJ5bDgtLXLyxXhZRE7vUd06DIUyB8UnYIA1kSCkqwmYg7w2SIEUK7yJHxd7YAnQX8ny3vY1CJY1PuHZlus2jku1XRoNCThVmxTEBQLeKfXAuxNfIVgAkcn/q2epjsE98hNF0UouFARpwt4ehH/Wsu26vB/Q6yDNUsfJfRJJW7RGEluW8B27/JitPEEDbc7FR7Ap+R3pKjs9UBVJDI4RUwpXzPjkcXedRL21PXYZ23pMmzloljrWSCJhcI5x6kcZQzbNWj6mAFajeyVIr5HWkKLMx06sKwGYYDwcQXgQqRjOFR0="
    on:
      tags: true
      condition: $TOXENV = "py36-dj111"
  - provider: pages
    local_dir: site
    skip-cleanup: true
    keep-history: true
    github_token: $GITHUB_TOKEN
    on:
      tags: true
      condition: $TOXENV = "docs"
